# Generated by Django 5.1.1 on 2024-10-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiresolver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='Parameters',
            field=models.JSONField(default=dict),
        ),
    ]
