# Generated by Django 5.1.1 on 2024-10-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiresolver', '0002_api_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.TextField(),
        ),
    ]
