# Generated by Django 5.1.1 on 2024-10-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiresolver', '0003_alter_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='Parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
