# Generated by Django 5.1.1 on 2024-10-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiresolver', '0004_alter_api_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='Parameters',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
    ]
